### ISSUE TITLE
Playnite to sync to HLTB DB

### ISSUE THREAD

**Issue by Trigger911** [Lacro59/playnite-howlongtobeat-plugin#251]
Excuse me for  asking this I feel kind of out of the place asking this. I was wanting my Playnite to sync to Howlongtobeat.com. I don't want to mess up my data but is there anyone that can explain this to me? I looked this up on google but I couldn't find a straight answer. Thanks in advance and thanks for the epic Add-on!

**Comment by celozzip** [comment]
Just installed playnite and this plugin. Looking at previous reports and patches it seems to break over and over again so they must be doing something at HLTB to break it?  It read all the stats from the site but can't write back to it because the search doesn't work so I can't associate any games with their HLTB entries?

**Comment by Lacro59** [comment]
#252
